### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [ri58-sibsutis/crypt#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/ri58-sibsutis/crypt/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/ri58-sibsutis/crypt/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by alexgorovenko** [comment]
Проверка ТЗ
@evgeny-p

**Comment by evgeny-p** [comment]
По первому пункту ТЗ кажется, что приложение работает только с файлами, имена которых равны `input` и `output`.

Какое поведение ожидается, если пользователь не указал выходного файла, а файл output уже существует?

> Если в файл «input» ничего не записано, то пользователь должен сам выбрать алгоритм шифрования, введя номер этого алгоритма в окне программы.

Т.е. в файле `input` помимо текста должен быть указан алгоритм шифрования?

Как приложение определяет: читать данные со стандартного потока ввода или из файла?

> Аргументы командной строки

Формальное описание лучше словесного. См synopsis любой man-страницы, например [grep](http://linux.die.net/man/1/grep).

П. 5 можно просто убрать.

**Comment by janbaton** [comment]
На Wiki созданы страницы "Техническая документация" и "Техническое задание"
