### ISSUE TITLE
Алгоритм Цезаря

### ISSUE THREAD

**Issue by alexgorovenko** [ri58-sibsutis/crypt#3]
Реализовать алгоритм Цезаря.

@evgeny-p

**Comment by level55** [comment]
Реализован шифр Цезаря. Работа алгоритма заключается в том, что каждый символ в введённой пользователем строке заменяется символом находящимся на заданном пользователем (переменная shift) числе позиций справа в алфавите. Числа не шифруются никаким образом. На вход при считывании сдвига должно подаваться только число.
