### ISSUE TITLE
Аффинный шифр

### ISSUE THREAD

**Issue by alexgorovenko** [ri58-sibsutis/crypt#5]
Реализовать аффинный шифр.

@evgeny-p

**Comment by level55** [comment]
Реализован аффинный шифр. Работа алгоритма заключается в том, что находится позиция (номер) каждого символа из введённой пользователем строки в алфавите (для алфавита в алгоритме заведена таблица) и в дальнейшем с помощью функции 'Encrypt' происходит изменение номера символа. По измененному номеру находится символ в алфавите и заменяет изначальный символ. 
Изменение номера символа происходит в функции Encrypt по формуле y = (a \* x + b) % m , где m = 26 (в используемом алфавите 26 букв). Учтено то, что 'a' и 'm' должны быть взаимно простыми числами (используется функция Gcd для проверки этого условия) и 'a' должно быть не равно 1. На вход при считывании 'a' и 'b' должны подаваться только числа.
