### ISSUE TITLE
Создание Makefile и структуры проекта

### ISSUE THREAD

**Issue by alexgorovenko** [ri58-sibsutis/crypt#6]
Написать Makefile и создать папки под разные части проекта.

@evgeny-p

**Comment by level55** [comment]
Создана общая структура проекта, .c и .h файлы разложены по папкам. Создан Makefile, пока что не включающий в себя сборку с шифром Вернама.

**Comment by level55** [comment]
Изменён Makefile. Добавлена сборка с шифром Вернама.
